//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServicesSoap", Namespace="http://geolearning.com/geonext/webservices/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Persistent))]
public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback UserExistsByExternalIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback LoadUserByExternalIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback UserExistsByUniqueIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback LoadUserByUniqueIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback LoadUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback GenerateUserObjectOperationCompleted;
    
    private System.Threading.SendOrPostCallback UserExistsOperationCompleted;
    
    /// <remarks/>
    public WebServices() {
        this.Url = "https://localhost/Geonext/webservices/geonext.asmx";
    }
    
    /// <remarks/>
    public event UserExistsByExternalIdCompletedEventHandler UserExistsByExternalIdCompleted;
    
    /// <remarks/>
    public event LoadUserByExternalIdCompletedEventHandler LoadUserByExternalIdCompleted;
    
    /// <remarks/>
    public event UserExistsByUniqueIdCompletedEventHandler UserExistsByUniqueIdCompleted;
    
    /// <remarks/>
    public event LoadUserByUniqueIdCompletedEventHandler LoadUserByUniqueIdCompleted;
    
    /// <remarks/>
    public event CreateUserCompletedEventHandler CreateUserCompleted;
    
    /// <remarks/>
    public event UpdateUserCompletedEventHandler UpdateUserCompleted;
    
    /// <remarks/>
    public event LoadUserCompletedEventHandler LoadUserCompleted;
    
    /// <remarks/>
    public event GenerateUserObjectCompletedEventHandler GenerateUserObjectCompleted;
    
    /// <remarks/>
    public event UserExistsCompletedEventHandler UserExistsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/UserExistsByExternalId", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool UserExistsByExternalId(string externalId) {
        object[] results = this.Invoke("UserExistsByExternalId", new object[] {
                    externalId});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUserExistsByExternalId(string externalId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UserExistsByExternalId", new object[] {
                    externalId}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndUserExistsByExternalId(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void UserExistsByExternalIdAsync(string externalId) {
        this.UserExistsByExternalIdAsync(externalId, null);
    }
    
    /// <remarks/>
    public void UserExistsByExternalIdAsync(string externalId, object userState) {
        if ((this.UserExistsByExternalIdOperationCompleted == null)) {
            this.UserExistsByExternalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserExistsByExternalIdOperationCompleted);
        }
        this.InvokeAsync("UserExistsByExternalId", new object[] {
                    externalId}, this.UserExistsByExternalIdOperationCompleted, userState);
    }
    
    private void OnUserExistsByExternalIdOperationCompleted(object arg) {
        if ((this.UserExistsByExternalIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UserExistsByExternalIdCompleted(this, new UserExistsByExternalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/LoadUserByExternalId", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public User LoadUserByExternalId(string externalId) {
        object[] results = this.Invoke("LoadUserByExternalId", new object[] {
                    externalId});
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLoadUserByExternalId(string externalId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LoadUserByExternalId", new object[] {
                    externalId}, callback, asyncState);
    }
    
    /// <remarks/>
    public User EndLoadUserByExternalId(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public void LoadUserByExternalIdAsync(string externalId) {
        this.LoadUserByExternalIdAsync(externalId, null);
    }
    
    /// <remarks/>
    public void LoadUserByExternalIdAsync(string externalId, object userState) {
        if ((this.LoadUserByExternalIdOperationCompleted == null)) {
            this.LoadUserByExternalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUserByExternalIdOperationCompleted);
        }
        this.InvokeAsync("LoadUserByExternalId", new object[] {
                    externalId}, this.LoadUserByExternalIdOperationCompleted, userState);
    }
    
    private void OnLoadUserByExternalIdOperationCompleted(object arg) {
        if ((this.LoadUserByExternalIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoadUserByExternalIdCompleted(this, new LoadUserByExternalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/UserExistsByUniqueId", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool UserExistsByUniqueId(string uniqueId) {
        object[] results = this.Invoke("UserExistsByUniqueId", new object[] {
                    uniqueId});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUserExistsByUniqueId(string uniqueId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UserExistsByUniqueId", new object[] {
                    uniqueId}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndUserExistsByUniqueId(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void UserExistsByUniqueIdAsync(string uniqueId) {
        this.UserExistsByUniqueIdAsync(uniqueId, null);
    }
    
    /// <remarks/>
    public void UserExistsByUniqueIdAsync(string uniqueId, object userState) {
        if ((this.UserExistsByUniqueIdOperationCompleted == null)) {
            this.UserExistsByUniqueIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserExistsByUniqueIdOperationCompleted);
        }
        this.InvokeAsync("UserExistsByUniqueId", new object[] {
                    uniqueId}, this.UserExistsByUniqueIdOperationCompleted, userState);
    }
    
    private void OnUserExistsByUniqueIdOperationCompleted(object arg) {
        if ((this.UserExistsByUniqueIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UserExistsByUniqueIdCompleted(this, new UserExistsByUniqueIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/LoadUserByUniqueId", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public User LoadUserByUniqueId(string uniqueId) {
        object[] results = this.Invoke("LoadUserByUniqueId", new object[] {
                    uniqueId});
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLoadUserByUniqueId(string uniqueId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LoadUserByUniqueId", new object[] {
                    uniqueId}, callback, asyncState);
    }
    
    /// <remarks/>
    public User EndLoadUserByUniqueId(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public void LoadUserByUniqueIdAsync(string uniqueId) {
        this.LoadUserByUniqueIdAsync(uniqueId, null);
    }
    
    /// <remarks/>
    public void LoadUserByUniqueIdAsync(string uniqueId, object userState) {
        if ((this.LoadUserByUniqueIdOperationCompleted == null)) {
            this.LoadUserByUniqueIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUserByUniqueIdOperationCompleted);
        }
        this.InvokeAsync("LoadUserByUniqueId", new object[] {
                    uniqueId}, this.LoadUserByUniqueIdOperationCompleted, userState);
    }
    
    private void OnLoadUserByUniqueIdOperationCompleted(object arg) {
        if ((this.LoadUserByUniqueIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoadUserByUniqueIdCompleted(this, new LoadUserByUniqueIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/CreateUser", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public UserResult CreateUser(User user) {
        object[] results = this.Invoke("CreateUser", new object[] {
                    user});
        return ((UserResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateUser(User user, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateUser", new object[] {
                    user}, callback, asyncState);
    }
    
    /// <remarks/>
    public UserResult EndCreateUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((UserResult)(results[0]));
    }
    
    /// <remarks/>
    public void CreateUserAsync(User user) {
        this.CreateUserAsync(user, null);
    }
    
    /// <remarks/>
    public void CreateUserAsync(User user, object userState) {
        if ((this.CreateUserOperationCompleted == null)) {
            this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
        }
        this.InvokeAsync("CreateUser", new object[] {
                    user}, this.CreateUserOperationCompleted, userState);
    }
    
    private void OnCreateUserOperationCompleted(object arg) {
        if ((this.CreateUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/UpdateUser", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Result UpdateUser(User user) {
        object[] results = this.Invoke("UpdateUser", new object[] {
                    user});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateUser(User user, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateUser", new object[] {
                    user}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndUpdateUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateUserAsync(User user) {
        this.UpdateUserAsync(user, null);
    }
    
    /// <remarks/>
    public void UpdateUserAsync(User user, object userState) {
        if ((this.UpdateUserOperationCompleted == null)) {
            this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
        }
        this.InvokeAsync("UpdateUser", new object[] {
                    user}, this.UpdateUserOperationCompleted, userState);
    }
    
    private void OnUpdateUserOperationCompleted(object arg) {
        if ((this.UpdateUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/LoadUser", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public User LoadUser(string userName) {
        object[] results = this.Invoke("LoadUser", new object[] {
                    userName});
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLoadUser(string userName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LoadUser", new object[] {
                    userName}, callback, asyncState);
    }
    
    /// <remarks/>
    public User EndLoadUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public void LoadUserAsync(string userName) {
        this.LoadUserAsync(userName, null);
    }
    
    /// <remarks/>
    public void LoadUserAsync(string userName, object userState) {
        if ((this.LoadUserOperationCompleted == null)) {
            this.LoadUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadUserOperationCompleted);
        }
        this.InvokeAsync("LoadUser", new object[] {
                    userName}, this.LoadUserOperationCompleted, userState);
    }
    
    private void OnLoadUserOperationCompleted(object arg) {
        if ((this.LoadUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoadUserCompleted(this, new LoadUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/GenerateUserObject", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public User GenerateUserObject() {
        object[] results = this.Invoke("GenerateUserObject", new object[0]);
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGenerateUserObject(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GenerateUserObject", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public User EndGenerateUserObject(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((User)(results[0]));
    }
    
    /// <remarks/>
    public void GenerateUserObjectAsync() {
        this.GenerateUserObjectAsync(null);
    }
    
    /// <remarks/>
    public void GenerateUserObjectAsync(object userState) {
        if ((this.GenerateUserObjectOperationCompleted == null)) {
            this.GenerateUserObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateUserObjectOperationCompleted);
        }
        this.InvokeAsync("GenerateUserObject", new object[0], this.GenerateUserObjectOperationCompleted, userState);
    }
    
    private void OnGenerateUserObjectOperationCompleted(object arg) {
        if ((this.GenerateUserObjectCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GenerateUserObjectCompleted(this, new GenerateUserObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://geolearning.com/geonext/webservices/UserExists", RequestNamespace="http://geolearning.com/geonext/webservices/", ResponseNamespace="http://geolearning.com/geonext/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool UserExists(string userName) {
        object[] results = this.Invoke("UserExists", new object[] {
                    userName});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUserExists(string userName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UserExists", new object[] {
                    userName}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndUserExists(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void UserExistsAsync(string userName) {
        this.UserExistsAsync(userName, null);
    }
    
    /// <remarks/>
    public void UserExistsAsync(string userName, object userState) {
        if ((this.UserExistsOperationCompleted == null)) {
            this.UserExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserExistsOperationCompleted);
        }
        this.InvokeAsync("UserExists", new object[] {
                    userName}, this.UserExistsOperationCompleted, userState);
    }
    
    private void OnUserExistsOperationCompleted(object arg) {
        if ((this.UserExistsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UserExistsCompleted(this, new UserExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public partial class User : Persistent {
    
    private string firstNameField;
    
    private string middleInitialField;
    
    private string lastNameField;
    
    private string emailField;
    
    private string streetAddressField;
    
    private string streetAddress2Field;
    
    private string cityField;
    
    private string stateField;
    
    private string countryField;
    
    private string postalCodeField;
    
    private PostalCodeType postalCodeTypeField;
    
    private string telephoneField;
    
    private string extensionField;
    
    private string locationNameField;
    
    private System.DateTime startDateField;
    
    private string userNameField;
    
    private string passwordField;
    
    private System.DateTime birthDateField;
    
    private string socialSecurityNumberField;
    
    private string[] supervisorUserNamesField;
    
    private Group[] groupsField;
    
    private string[] roleNamesField;
    
    private string defaultRoleNameField;
    
    private string externalIdField;
    
    private string timeZoneField;
    
    private string currencyField;
    
    private string languageField;
    
    private string eHRIEmployeeIDField;
    
    private string agencySubElementCodeField;
    
    private string doChangePasswordNextLoginField;
    
    private string uniqueIdField;
    
    private CustomUserAttribute[] customUserAttributesField;
    
    private CustomUserAttribute[] customSelectUserAttributesField;
    
    private string[] catalogAccessCodeNamesField;
    
    private string directSupervisorNameField;
    
    private bool receiveAutomatedEmailsField;
    
    private ProfileOwner ownerField;
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleInitial {
        get {
            return this.middleInitialField;
        }
        set {
            this.middleInitialField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string StreetAddress {
        get {
            return this.streetAddressField;
        }
        set {
            this.streetAddressField = value;
        }
    }
    
    /// <remarks/>
    public string StreetAddress2 {
        get {
            return this.streetAddress2Field;
        }
        set {
            this.streetAddress2Field = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public PostalCodeType PostalCodeType {
        get {
            return this.postalCodeTypeField;
        }
        set {
            this.postalCodeTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    public string Extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    public string LocationName {
        get {
            return this.locationNameField;
        }
        set {
            this.locationNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    public string SocialSecurityNumber {
        get {
            return this.socialSecurityNumberField;
        }
        set {
            this.socialSecurityNumberField = value;
        }
    }
    
    /// <remarks/>
    public string[] SupervisorUserNames {
        get {
            return this.supervisorUserNamesField;
        }
        set {
            this.supervisorUserNamesField = value;
        }
    }
    
    /// <remarks/>
    public Group[] Groups {
        get {
            return this.groupsField;
        }
        set {
            this.groupsField = value;
        }
    }
    
    /// <remarks/>
    public string[] RoleNames {
        get {
            return this.roleNamesField;
        }
        set {
            this.roleNamesField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultRoleName {
        get {
            return this.defaultRoleNameField;
        }
        set {
            this.defaultRoleNameField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    public string TimeZone {
        get {
            return this.timeZoneField;
        }
        set {
            this.timeZoneField = value;
        }
    }
    
    /// <remarks/>
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string EHRIEmployeeID {
        get {
            return this.eHRIEmployeeIDField;
        }
        set {
            this.eHRIEmployeeIDField = value;
        }
    }
    
    /// <remarks/>
    public string AgencySubElementCode {
        get {
            return this.agencySubElementCodeField;
        }
        set {
            this.agencySubElementCodeField = value;
        }
    }
    
    /// <remarks/>
    public string DoChangePasswordNextLogin {
        get {
            return this.doChangePasswordNextLoginField;
        }
        set {
            this.doChangePasswordNextLoginField = value;
        }
    }
    
    /// <remarks/>
    public string UniqueId {
        get {
            return this.uniqueIdField;
        }
        set {
            this.uniqueIdField = value;
        }
    }
    
    /// <remarks/>
    public CustomUserAttribute[] CustomUserAttributes {
        get {
            return this.customUserAttributesField;
        }
        set {
            this.customUserAttributesField = value;
        }
    }
    
    /// <remarks/>
    public CustomUserAttribute[] CustomSelectUserAttributes {
        get {
            return this.customSelectUserAttributesField;
        }
        set {
            this.customSelectUserAttributesField = value;
        }
    }
    
    /// <remarks/>
    public string[] CatalogAccessCodeNames {
        get {
            return this.catalogAccessCodeNamesField;
        }
        set {
            this.catalogAccessCodeNamesField = value;
        }
    }
    
    /// <remarks/>
    public string DirectSupervisorName {
        get {
            return this.directSupervisorNameField;
        }
        set {
            this.directSupervisorNameField = value;
        }
    }
    
    /// <remarks/>
    public bool ReceiveAutomatedEmails {
        get {
            return this.receiveAutomatedEmailsField;
        }
        set {
            this.receiveAutomatedEmailsField = value;
        }
    }
    
    /// <remarks/>
    public ProfileOwner Owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public enum PostalCodeType {
    
    /// <remarks/>
    APO,
    
    /// <remarks/>
    Foreign,
    
    /// <remarks/>
    US,
    
    /// <remarks/>
    Undefined,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public partial class Group {
    
    private string nameField;
    
    private string codeField;
    
    private bool isDefaultField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public bool IsDefault {
        get {
            return this.isDefaultField;
        }
        set {
            this.isDefaultField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserResult))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public partial class Result {
    
    private string[] errorsField;
    
    private string[] warningsField;
    
    /// <remarks/>
    public string[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    public string[] Warnings {
        get {
            return this.warningsField;
        }
        set {
            this.warningsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public partial class UserResult : Result {
    
    private string defaultPasswordField;
    
    /// <remarks/>
    public string DefaultPassword {
        get {
            return this.defaultPasswordField;
        }
        set {
            this.defaultPasswordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public partial class CustomUserAttribute {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public abstract partial class Persistent {
    
    private Status statusField;
    
    private System.DateTime creationTimeField;
    
    private System.DateTime modifiedTimeField;
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreationTime {
        get {
            return this.creationTimeField;
        }
        set {
            this.creationTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ModifiedTime {
        get {
            return this.modifiedTimeField;
        }
        set {
            this.modifiedTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public enum Status {
    
    /// <remarks/>
    Active,
    
    /// <remarks/>
    Archived,
    
    /// <remarks/>
    Inactive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://geolearning.com/geonext/webservices/")]
public enum ProfileOwner {
    
    /// <remarks/>
    LMS,
    
    /// <remarks/>
    External,
    
    /// <remarks/>
    SumTotal,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UserExistsByExternalIdCompletedEventHandler(object sender, UserExistsByExternalIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UserExistsByExternalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UserExistsByExternalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LoadUserByExternalIdCompletedEventHandler(object sender, LoadUserByExternalIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoadUserByExternalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoadUserByExternalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public User Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((User)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UserExistsByUniqueIdCompletedEventHandler(object sender, UserExistsByUniqueIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UserExistsByUniqueIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UserExistsByUniqueIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LoadUserByUniqueIdCompletedEventHandler(object sender, LoadUserByUniqueIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoadUserByUniqueIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoadUserByUniqueIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public User Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((User)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public UserResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UserResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LoadUserCompletedEventHandler(object sender, LoadUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoadUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoadUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public User Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((User)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GenerateUserObjectCompletedEventHandler(object sender, GenerateUserObjectCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GenerateUserObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GenerateUserObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public User Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((User)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UserExistsCompletedEventHandler(object sender, UserExistsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UserExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UserExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
